import { MetadataRoute } from 'next';
import autoGeneratedTools from '@/lib/autoGeneratedTools.json';
import examPresets from '@/data/exam-presets.json';

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.formilo.in';

export default function sitemap(): MetadataRoute.Sitemap {
  const currentDate = new Date();
  const urlMap = new Map<string, MetadataRoute.Sitemap[number]>();

  const registerUrl = (
    path: string,
    priority: number,
    changeFrequency: 'daily' | 'weekly' | 'monthly' = 'weekly'
  ) => {
    if (!path) return;
    const cleanPath = path.startsWith('/') ? path : `/${path}`;
    const fullUrl = `${BASE_URL}${cleanPath}`.toLowerCase().trim();

    if (!urlMap.has(fullUrl)) {
      urlMap.set(fullUrl, {
        url: fullUrl,
        lastModified: currentDate,
        changeFrequency,
        priority,
      });
    }
  };

  // 1. Core High-Priority Static Routes
  registerUrl('/', 1.0, 'daily');
  registerUrl('/cyber-cafe', 0.95, 'daily');
  registerUrl('/name-date-on-photo', 0.95, 'daily');
  registerUrl('/privacy', 0.3, 'monthly');
  registerUrl('/terms', 0.3, 'monthly');

  // 2. Dedicated KB Landing Pages
  registerUrl('/photo-resizer-20kb', 0.95, 'weekly');
  registerUrl('/photo-resizer-30kb', 0.90, 'weekly');
  registerUrl('/photo-resizer-50kb', 0.95, 'weekly');
  registerUrl('/photo-resizer-100kb', 0.90, 'weekly');
  registerUrl('/photo-resizer-150kb', 0.85, 'weekly');
  registerUrl('/photo-resizer-200kb', 0.90, 'weekly');

  // 3. Category Hub Pages
  registerUrl('/form-tools', 0.85, 'weekly');
  registerUrl('/photo-tools', 0.85, 'weekly');
  registerUrl('/signature-tools', 0.85, 'weekly');
  registerUrl('/pdf-tools', 0.85, 'weekly');
  registerUrl('/image-tools', 0.85, 'weekly');

  // 4. Document & Utility Tools
  registerUrl('/tools/jpg-to-pdf-converter', 0.90, 'weekly');
  registerUrl('/tools/pdf-to-jpg-converter', 0.85, 'weekly');
  registerUrl('/tools/pdf-compressor-under-200kb', 0.90, 'weekly');
  registerUrl('/tools/make-background-white-of-signature', 0.90, 'weekly');
  registerUrl('/exam/photo-watermark-remover', 0.80, 'weekly');

  // 5. Auto-Generated Programmatic SEO Tools (800+ Live URLs)
  if (Array.isArray(autoGeneratedTools)) {
    autoGeneratedTools.forEach((tool: any) => {
      if (tool.slug) {
        registerUrl(tool.slug, 0.85, 'weekly');
      }
    });
  }

  // 6. Base Exam Preset Hubs
  if (Array.isArray(examPresets)) {
    examPresets.forEach((exam: any) => {
      if (exam.slug) {
        const examPath = exam.slug.startsWith('exam/') ? `/${exam.slug}` : `/exam/${exam.slug}`;
        registerUrl(examPath, 0.80, 'weekly');
      }
    });
  }

  return Array.from(urlMap.values());
}
