// lib/registryResolver.ts

import {
  MASTER_TOOL_REGISTRY,
  ToolConfig,
  ToolType,
  calculateAspectRatio,
} from '@/data/masterRegistry';
import autoGeneratedTools from '@/lib/autoGeneratedTools.json';

// Helper to sanitize and normalize slugs
export function normalizeSlug(rawSlug: string): string {
  return (rawSlug || '')
    .toLowerCase()
    .replace(/^\/+|\/+$/g, '')
    .trim();
}

// Convert a clean slug to a readable title
function slugToTitle(slug: string): string {
  const base = slug
    .replace(/^(exam|tools)\//, '')
    .replace(/-/g, ' ');
  return base
    .split(' ')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

// Strict ToolType detection from string context
export function detectToolTypeFromSlug(cleanSlug: string): ToolType {
  const s = cleanSlug.toLowerCase();
  if (s.includes('signature') || s.includes('-sign-') || s.includes('thumb')) {
    if (s.includes('crop')) return 'SIGNATURE_CROPPER';
    if (s.includes('compress')) return 'SIGNATURE_COMPRESSOR';
    return 'SIGNATURE_RESIZER';
  }
  if (s.includes('thumb-impression')) return 'THUMB_IMPRESSION';
  if (s.includes('name-date') || s.includes('dop')) return 'NAME_DATE_PHOTO';
  if (s.includes('jpg-to-pdf') || s.includes('image-to-pdf')) return 'JPG_TO_PDF';
  if (s.includes('pdf-to-jpg')) return 'PDF_TO_JPG';
  if (s.includes('pdf-compress') || s.includes('compress-pdf')) return 'PDF_COMPRESSOR';
  if (s.includes('photo-compress') || s.includes('compress-photo')) return 'PHOTO_COMPRESSOR';
  return 'PHOTO_RESIZER';
}

/**
 * RESOLVE TOOL CONFIG WITH ABSOLUTE ISOLATION
 * Guaranteed zero cross-contamination.
 */
export function resolveToolConfig(rawSlug: string): ToolConfig {
  const cleanSlug = normalizeSlug(rawSlug);
  const slugBase = cleanSlug.replace(/^(exam|tools)\//, '');

  // 1. Direct Lookup in Master Registry
  if (MASTER_TOOL_REGISTRY[slugBase]) {
    return MASTER_TOOL_REGISTRY[slugBase];
  }
  for (const key of Object.keys(MASTER_TOOL_REGISTRY)) {
    const item = MASTER_TOOL_REGISTRY[key];
    if (normalizeSlug(item.slug) === cleanSlug || item.id === slugBase) {
      return item;
    }
  }

  // 2. Safe Auto-Generated Catalog Resolution
  // Read ONLY the matched entry's own fields. Do not inject any outside exam constants.
  const matchedAuto = (autoGeneratedTools as any[]).find((tool) => {
    const s = normalizeSlug(tool.slug || '');
    const sBase = s.replace(/^(exam|tools)\//, '');
    const id = normalizeSlug(tool.id || '');
    return s === cleanSlug || sBase === slugBase || id === slugBase;
  });

  const toolType = detectToolTypeFromSlug(cleanSlug);
  const isSignature = toolType.startsWith('SIGNATURE') || toolType === 'THUMB_IMPRESSION';
  const isPdf = toolType === 'PDF_COMPRESSOR' || toolType === 'JPG_TO_PDF' || toolType === 'PDF_TO_JPG';

  // Strict dynamic dimensions and target limits based on toolType
  let width = 350;
  let height = 450;
  let targetKB = 50;
  let minKB = 10;
  let dimensionsText = '350 × 450 px';

  if (isSignature) {
    width = 280;
    height = 120;
    targetKB = 20;
    minKB = 5;
    dimensionsText = '280 × 120 px';
  } else if (cleanSlug.includes('postcard') || cleanSlug.includes('4x6')) {
    width = 400;
    height = 720;
    targetKB = 200;
    minKB = 50;
    dimensionsText = '400 × 720 px (4 × 6 Inch)';
  } else if (cleanSlug.includes('pan-card')) {
    width = 213;
    height = 213;
    targetKB = 50;
    minKB = 10;
    dimensionsText = '213 × 213 px';
  }

  // Override if explicitly defined on this specific entry
  if (matchedAuto?.targetKB) targetKB = matchedAuto.targetKB;
  if (matchedAuto?.width && matchedAuto?.height) {
    width = matchedAuto.width;
    height = matchedAuto.height;
    dimensionsText = `${width} × ${height} px`;
  }

  // Determine Title & Exam Name independently
  const title = matchedAuto?.name || matchedAuto?.title || slugToTitle(slugBase);
  const examName = matchedAuto?.exam || matchedAuto?.examName || slugToTitle(slugBase.replace(/-(photo|signature|resizer|compress).*$/, ''));
  const authorityName = matchedAuto?.board || 'Official Recruitment Authority';

  // Construct isolated safe fallback
  const safeConfig: ToolConfig = {
    id: slugBase,
    slug: cleanSlug,
    category: isSignature ? 'signature' : isPdf ? 'pdf' : 'photo',
    toolType,
    examId: slugBase.replace(/-(passport-size-photo-resizer|signature-crop-compress|pdf-compressor).*$/, ''),
    authorityId: 'general',
    examName,
    authorityName,
    title,
    shortDescription: matchedAuto?.description || `Prepare and format documents strictly for ${title} official application portal submission.`,
    requirements: {
      dimensions: dimensionsText,
      width,
      height,
      minKB,
      targetKB,
      maxKB: targetKB,
      format: isPdf ? 'PDF' : 'JPG / JPEG',
      aspectRatio: calculateAspectRatio(width, height),
      background: isSignature ? 'Clean white paper background' : 'Clean light or white background',
      expressionOrInk: isSignature ? 'Candidate signature in dark ink' : 'Straight facial posture with clear eye visibility',
      dpi: 300,
    },
    officialSource: {
      authorityName,
      portalUrl: '#',
      linkLabel: 'Official Recruitment Portal',
    },
    content: {
      requirementHeading: `${examName} Requirements`,
      preparationTips: [
        `Ensure ${isSignature ? 'the signature' : 'your photo'} complies with the required framing.`,
        'Process locally inside your device without network distortion.',
        'Verify contrast and legibility before uploading to the portal.',
      ],
      rejectionReasons: [
        `File size exceeding ${targetKB} KB limit.`,
        'Distorted aspect ratio or stretched features.',
        'Improper background contrast or illegible capture.',
      ],
      instructions: [
        `Upload your ${isSignature ? 'signature' : 'photograph'}.`,
        'Align framing with the live guidelines.',
        `Compress locally under ${targetKB} KB.`,
        'Download the verified compliant file.',
      ],
      mobileInstructions: [
        'Tap Choose Image to upload from your smartphone gallery.',
        'Adjust the scale slider to fit the bounding box.',
        'Tap Download; the file saves directly to your device storage.',
      ],
      checklist: [
        `Dimensions: ${dimensionsText}`,
        `File size: ${minKB} KB – ${targetKB} KB`,
        `Format: ${isPdf ? 'PDF' : 'JPG / JPEG'}`,
        'Check latest official recruitment notification before submission',
      ],
      faqs: [
        {
          q: `What is the required size for ${title}?`,
          a: `Standard guidelines require dimensions of ${dimensionsText} with file size strictly under ${targetKB} KB.`,
        },
        {
          q: 'Does Formilo upload my files to an external server?',
          a: 'No. All image cropping and compression operations run 100% locally within your browser memory (RAM).',
        },
        {
          q: 'Should I verify the latest official notification?',
          a: `Yes. Guidelines can change between recruitment cycles. Always check the official notification for ${examName} before submitting your form.`,
        },
      ],
    },
    seo: {
      title: `${title} – Size & KB | Formilo`,
      description: `Prepare your ${title} with the required dimensions, file size and format. Free browser-based tool with no server upload.`,
      h1: title,
      canonicalSlug: cleanSlug,
    },
    verificationStatus: 'needs_review',
    lastVerified: '2026-05',
  };

  return safeConfig;
}
