import rawGeneratedToolsData from './autoGeneratedTools.json';

export interface ToolItem {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: 'photo' | 'signature' | 'pdf' | 'exam' | 'smart' | 'converters';
  badge?: string;
  targetKB: number;
  minKB?: number;
  width: number;
  height: number;
  dpi?: number;
  dimensionText?: string;
  isFeatured?: boolean;
  route?: string;
}

// 1. Base Core & Featured Tools
export const CORE_TOOLS: ToolItem[] = [
  {
    id: 'name-date-photo-generator',
    slug: 'name-date-on-photo',
    title: 'Name & Date on Photo (DOP / DOB) Generator',
    description: 'Add candidate name and photo date strip on passport photo strictly under 50 KB for SSC, RRB & Police forms.',
    category: 'photo',
    badge: 'NEW 2026',
    targetKB: 50,
    width: 350,
    height: 450,
    dimensionText: '350 × 450 px',
    isFeatured: true,
    route: '/name-date-on-photo'
  },
  {
    id: 'pan-card-photo-resizer',
    slug: 'pan-card-photo-resizer',
    title: 'PAN Card Photo Resizer (213 x 213 px)',
    description: 'Resize passport photo to exact 213x213 px and 300 DPI for NSDL and UTIITSL online portal forms.',
    category: 'photo',
    badge: 'PAN NSDL',
    targetKB: 50,
    width: 213,
    height: 213,
    dpi: 300,
    dimensionText: '213 × 213 px',
    isFeatured: true,
    route: '/exam/pan-card-photo-resizer'
  },
  {
    id: 'pan-card-signature-resizer',
    slug: 'pan-card-signature-resizer',
    title: 'PAN Card Signature Resizer (400 x 200 px)',
    description: 'Compress signature to exact 400x200 px, 300 DPI and under 30 KB with sharp black & white contrast.',
    category: 'signature',
    badge: 'PAN NSDL',
    targetKB: 30,
    width: 400,
    height: 200,
    dpi: 300,
    dimensionText: '400 × 200 px',
    isFeatured: true,
    route: '/exam/pan-card-signature-resizer'
  },
  {
    id: 'photo-resize-20kb',
    slug: 'photo-resize-to-20kb',
    title: 'Photo Resize to 20 KB',
    description: 'Compress and resize passport photos strictly under 20 KB for official government application portals.',
    category: 'photo',
    badge: 'POPULAR',
    targetKB: 20,
    width: 350,
    height: 450,
    dimensionText: '350 × 450 px',
    isFeatured: true,
    route: '/exam/photo-resize-to-20kb'
  },
  {
    id: 'photo-resize-50kb',
    slug: 'photo-resize-to-50kb',
    title: 'Photo Resize to 50 KB',
    description: 'Resize and compress photos under 50 KB while maintaining crisp facial clarity without blur.',
    category: 'photo',
    badge: 'POPULAR',
    targetKB: 50,
    width: 350,
    height: 450,
    dimensionText: '350 × 450 px',
    isFeatured: true,
    route: '/exam/photo-resize-to-50kb'
  },
  {
    id: 'signature-resize-20kb',
    slug: 'signature-resize-to-20kb',
    title: 'Signature Resize to 20 KB',
    description: 'Resize scanned signature photos strictly under 20 KB with sharp contrast on clean white background.',
    category: 'signature',
    badge: 'POPULAR',
    targetKB: 20,
    width: 280,
    height: 120,
    dimensionText: '280 × 120 px',
    isFeatured: true,
    route: '/exam/signature-resize-to-20kb'
  },
  {
    id: 'nielit-ccc-exam-photo-sign',
    slug: 'nielit-ccc-exam-photo-and-sign-resizer',
    title: 'NIELIT CCC Exam Photo & Sign Resizer',
    description: 'Format CCC form photos to 132x170 px and signature to 170x132 px (10 KB - 20 KB).',
    category: 'exam',
    badge: 'NIELIT',
    targetKB: 20,
    minKB: 10,
    width: 132,
    height: 170,
    dimensionText: '132 × 170 px',
    isFeatured: true,
    route: '/exam/nielit-ccc-exam-photo-and-sign-resizer'
  },
  {
    id: 'watermark-stamp-remover',
    slug: 'online-watermark-stamp-remover',
    title: 'Online Watermark & Stamp Remover',
    description: 'Erase unwanted watermarks, dates, stamps, and text from photos using browser inpainting technology.',
    category: 'smart',
    badge: 'SMART TOOL',
    targetKB: 100,
    width: 800,
    height: 800,
    dimensionText: 'Auto Clean',
    isFeatured: true,
    route: '/tools/online-watermark-stamp-remover'
  },
  {
    id: 'jpg-to-pdf-converter',
    slug: 'jpg-to-pdf-converter',
    title: 'JPG to PDF Converter',
    description: 'Combine multiple JPG, PNG, or WebP images into a single professional PDF document.',
    category: 'pdf',
    badge: 'PRO',
    targetKB: 500,
    width: 1240,
    height: 1754,
    dimensionText: 'Multi-Page A4',
    isFeatured: true,
    route: '/tools/jpg-to-pdf-converter'
  },
  {
    id: 'pdf-to-jpg-converter',
    slug: 'pdf-to-jpg-converter',
    title: 'PDF to JPG Converter',
    description: 'Extract PDF document pages into high-resolution JPG images directly inside browser RAM.',
    category: 'pdf',
    badge: 'FAST',
    targetKB: 500,
    width: 1240,
    height: 1754,
    dimensionText: '300 DPI HD',
    isFeatured: true,
    route: '/tools/pdf-to-jpg-converter'
  },
  {
    id: 'pdf-compressor-200kb',
    slug: 'pdf-compressor-under-200kb',
    title: 'PDF Compressor (< 200 KB)',
    description: 'Compress large PDF certificates, marksheets, and caste documents strictly under 200 KB.',
    category: 'pdf',
    badge: 'SAFE',
    targetKB: 200,
    width: 1240,
    height: 1754,
    dimensionText: 'Document Safe',
    isFeatured: true,
    route: '/tools/pdf-compressor-under-200kb'
  }
];

// 2. Strict Deduplication Engine with explicit any cast
function buildUniqueRegistry(): ToolItem[] {
  const toolMap = new Map<string, ToolItem>();

  // Add core tools first
  for (const tool of CORE_TOOLS) {
    const slugKey = tool.slug.toLowerCase().trim();
    toolMap.set(slugKey, tool);
  }

  // Cast imported JSON to any[] to satisfy TypeScript build
  const rawList = (rawGeneratedToolsData as any[]) || [];

  if (Array.isArray(rawList)) {
    for (const raw of rawList) {
      const rawSlug = String(raw.slug || raw.id || '').toLowerCase().trim();
      if (rawSlug && !toolMap.has(rawSlug)) {
        toolMap.set(rawSlug, {
          id: String(raw.id || rawSlug),
          slug: rawSlug,
          title: String(raw.title || rawSlug.replace(/-/g, ' ').toUpperCase()),
          description: String(raw.description || `Resize and format for online form under ${raw.targetKB || 50} KB.`),
          category: (raw.category as any) || 'exam',
          badge: raw.badge ? String(raw.badge) : 'EXAM',
          targetKB: Number(raw.targetKB) || 50,
          minKB: Number(raw.minKB) || 10,
          width: Number(raw.width) || 350,
          height: Number(raw.height) || 450,
          dpi: Number(raw.dpi) || 300,
          dimensionText: raw.dimensionText ? String(raw.dimensionText) : `${raw.width || 350} × ${raw.height || 450} px`,
          isFeatured: Boolean(raw.isFeatured),
          route: raw.route ? String(raw.route) : `/exam/${rawSlug}`
        });
      }
    }
  }

  return Array.from(toolMap.values());
}

// 3. Exports
export const verifiedTools: ToolItem[] = buildUniqueRegistry();
export const allTools: ToolItem[] = verifiedTools;
export const featuredTools: ToolItem[] = verifiedTools.filter((t) => t.isFeatured);

export function getToolBySlug(slug: string): ToolItem | undefined {
  if (!slug) return undefined;
  const clean = decodeURIComponent(slug).toLowerCase().trim();
  return verifiedTools.find(
    (t) => t.slug.toLowerCase().trim() === clean || t.id.toLowerCase().trim() === clean
  );
}

export function getToolsByCategory(category: string): ToolItem[] {
  return verifiedTools.filter(
    (t) => t.category.toLowerCase() === category.toLowerCase()
  );
}
