const fs = require('fs');
const path = require('path');

// Target output path
const outputPath = path.join(__dirname, '../lib/autoGeneratedTools.json');

// Unique Tool Registry Map (Ensures 0% Duplication)
const toolsMap = new Map();

function registerTool(tool) {
  const cleanSlug = tool.slug.toLowerCase().trim();
  if (!toolsMap.has(cleanSlug)) {
    toolsMap.set(cleanSlug, {
      ...tool,
      slug: cleanSlug,
      route: `/exam/${cleanSlug}`
    });
  }
}

// 1. Exam Definitions Matrix
const examsList = [
  // Staff Selection Commission (SSC)
  { name: 'SSC CGL 2026', short: 'ssc-cgl-2026', badge: 'SSC' },
  { name: 'SSC CHSL 2026', short: 'ssc-chsl-2026', badge: 'SSC' },
  { name: 'SSC MTS 2026', short: 'ssc-mts-2026', badge: 'SSC' },
  { name: 'SSC GD Constable 2026', short: 'ssc-gd-constable-2026', badge: 'SSC' },
  { name: 'SSC CPO Sub-Inspector', short: 'ssc-cpo-sub-inspector-2026', badge: 'SSC' },
  { name: 'SSC Stenographer', short: 'ssc-stenographer-2026', badge: 'SSC' },
  { name: 'SSC Selection Post Phase 12', short: 'ssc-selection-post-2026', badge: 'SSC' },

  // UPSC & Defence
  { name: 'UPSC Civil Services CSE', short: 'upsc-civil-services-cse-2026', badge: 'UPSC' },
  { name: 'UPSC NDA & NA Exam', short: 'upsc-nda-na-2026', badge: 'UPSC' },
  { name: 'UPSC CDS Examination', short: 'upsc-cds-2026', badge: 'UPSC' },
  { name: 'UPSC CAPF Assistant Commandant', short: 'upsc-capf-ac-2026', badge: 'UPSC' },
  { name: 'AFCAT Defence Exam', short: 'afcat-defence-2026', badge: 'DEFENCE' },
  { name: 'Indian Coast Guard Navik', short: 'indian-coast-guard-navik-2026', badge: 'DEFENCE' },

  // Railway Recruitment Board (RRB)
  { name: 'RRB NTPC Graduate & Under Graduate', short: 'rrb-ntpc-2026', badge: 'RAILWAY' },
  { name: 'RRB Group D Level 1', short: 'rrb-group-d-2026', badge: 'RAILWAY' },
  { name: 'RRB ALP Assistant Loco Pilot', short: 'rrb-alp-2026', badge: 'RAILWAY' },
  { name: 'RRB Technician Grade I & III', short: 'rrb-technician-2026', badge: 'RAILWAY' },
  { name: 'RRB Junior Engineer (JE)', short: 'rrb-je-2026', badge: 'RAILWAY' },

  // Banking & Insurance
  { name: 'IBPS PO Probationary Officer', short: 'ibps-po-2026', badge: 'BANKING' },
  { name: 'IBPS Clerk Exam', short: 'ibps-clerk-2026', badge: 'BANKING' },
  { name: 'SBI PO Examination', short: 'sbi-po-2026', badge: 'SBI' },
  { name: 'SBI Clerk Junior Associate', short: 'sbi-clerk-2026', badge: 'SBI' },
  { name: 'RBI Grade B Officer', short: 'rbi-grade-b-2026', badge: 'BANKING' },
  { name: 'LIC AAO Assistant Administrative Officer', short: 'lic-aao-2026', badge: 'INSURANCE' },

  // State Police Recruitment
  { name: 'UP Police Constable 2026', short: 'up-police-constable-2026', badge: 'UP POLICE' },
  { name: 'UP Police Sub Inspector SI', short: 'up-police-si-2026', badge: 'UP POLICE' },
  { name: 'Bihar Police Constable', short: 'bihar-police-constable-2026', badge: 'BIHAR POLICE' },
  { name: 'Bihar Police SI Daroga', short: 'bihar-police-si-2026', badge: 'BIHAR POLICE' },
  { name: 'Delhi Police Constable', short: 'delhi-police-constable-2026', badge: 'DELHI POLICE' },
  { name: 'Rajasthan Police Constable', short: 'rajasthan-police-constable-2026', badge: 'RAJ POLICE' },
  { name: 'MP Police Constable', short: 'mp-police-constable-2026', badge: 'MP POLICE' },
  { name: 'AP Police Constable Recruitment', short: 'ap-police-constable-recruitment-2026', badge: 'AP POLICE' },
  { name: 'Maharashtra Police Bharti', short: 'maharashtra-police-bharti-2026', badge: 'MAHA POLICE' },
  { name: 'West Bengal Police Constable', short: 'wb-police-constable-2026', badge: 'WB POLICE' },

  // National Entrance & Eligibility Exams
  { name: 'NEET UG Medical Entrance', short: 'neet-ug-medical-2026', badge: 'NTA' },
  { name: 'JEE Main Engineering Entrance', short: 'jee-main-2026', badge: 'NTA' },
  { name: 'CUET UG Common University Entrance', short: 'cuet-ug-2026', badge: 'NTA' },
  { name: 'GATE Engineering Exam', short: 'gate-exam-2026', badge: 'GATE' },
  { name: 'CTET Teacher Eligibility Test', short: 'ctet-exam-2026', badge: 'TEACHING' },

  // State Public Service Commissions (PSC)
  { name: 'BPSC Combined Competitive Exam', short: 'bpsc-cce-2026', badge: 'STATE PSC' },
  { name: 'UPPSC Combined State PCS', short: 'uppsc-pcs-2026', badge: 'STATE PSC' },
  { name: 'MPSC Rajyaseva Civil Exam', short: 'mpsc-rajyaseva-2026', badge: 'STATE PSC' },
  { name: 'MPPSC State Service Exam', short: 'mppsc-state-service-2026', badge: 'STATE PSC' },
  { name: 'TNPSC Group 4 & 2 Exam', short: 'tnpsc-group-exam-2026', badge: 'STATE PSC' },
  { name: 'TSPSC Group Services', short: 'tspsc-group-services-2026', badge: 'STATE PSC' }
];

// 2. Generate Standardized Document Presets for Each Exam
examsList.forEach((exam) => {
  // A. Passport Size Photo (20 KB - 50 KB)
  registerTool({
    id: `${exam.short}-passport-photo`,
    slug: `${exam.short}-passport-size-photo-resizer`,
    title: `${exam.name} Passport Size Photo Resizer`,
    description: `Free online passport size photo resizer for ${exam.name}. Compress strictly between 20 KB to 50 KB (350x450 px) with clean white background.`,
    category: 'exam',
    badge: exam.badge,
    targetKB: 50,
    minKB: 20,
    width: 350,
    height: 450,
    dpi: 300,
    dimensionText: '350 × 450 px',
    isFeatured: false
  });

  // B. Signature Crop & Compress (10 KB - 20 KB)
  registerTool({
    id: `${exam.short}-signature`,
    slug: `${exam.short}-signature-crop-compress`,
    title: `${exam.name} Signature Crop & Compress`,
    description: `Free online signature crop & compress under 20 KB for ${exam.name}. Crop signature on sharp white background with dark black/blue ink.`,
    category: 'signature',
    badge: 'SIGN',
    targetKB: 20,
    minKB: 10,
    width: 280,
    height: 120,
    dpi: 300,
    dimensionText: '280 × 120 px',
    isFeatured: false
  });

  // C. Left Thumb Impression Resizer (10 KB - 20 KB)
  registerTool({
    id: `${exam.short}-thumb`,
    slug: `${exam.short}-left-thumb-impression-resizer`,
    title: `${exam.name} Left Thumb Impression Resizer`,
    description: `Format candidate thumb print impression to blue/black ink under 20 KB for ${exam.name} official application portal.`,
    category: 'signature',
    badge: 'THUMB',
    targetKB: 20,
    minKB: 10,
    width: 240,
    height: 240,
    dpi: 300,
    dimensionText: '240 × 240 px',
    isFeatured: false
  });

  // D. Postcard Size Photo (4x6 Inch) Resizer (50 KB - 200 KB)
  registerTool({
    id: `${exam.short}-postcard-photo`,
    slug: `${exam.short}-postcard-size-photo-4x6-resizer`,
    title: `${exam.name} Postcard Size Photo (4x6 Inch) Resizer`,
    description: `Resize full postcard size 4x6 photograph with white background under 200 KB for ${exam.name}.`,
    category: 'photo',
    badge: '< 200 KB',
    targetKB: 200,
    minKB: 50,
    width: 480,
    height: 720,
    dpi: 300,
    dimensionText: '480 × 720 px',
    isFeatured: false
  });

  // E. Handwritten Declaration (For Banking & Specific Exams)
  if (['BANKING', 'SBI', 'INSURANCE'].includes(exam.badge)) {
    registerTool({
      id: `${exam.short}-declaration`,
      slug: `${exam.short}-handwritten-declaration-resizer`,
      title: `${exam.name} Handwritten Declaration Resizer`,
      description: `Compress and format official handwritten declaration image strictly between 50 KB to 100 KB for ${exam.name}.`,
      category: 'exam',
      badge: '50-100 KB',
      targetKB: 100,
      minKB: 50,
      width: 800,
      height: 400,
      dpi: 300,
      dimensionText: '800 × 400 px',
      isFeatured: false
    });
  }
});

// 3. Write Sanitized JSON File
const finalToolsList = Array.from(toolsMap.values());
fs.writeFileSync(outputPath, JSON.stringify(finalToolsList, null, 2), 'utf-8');

console.log(`Successfully generated ${finalToolsList.length} unique programmatic exam tools with 0 duplicates.`);
