const https = require('https');
const fs = require('fs');
const path = require('path');

const HOST = 'www.formilo.in';
const KEY = 'formilo-index-engine-2026';
const KEY_LOCATION = `https://${HOST}/${KEY}.txt`;

// 1. Core static routes & category hubs
const coreRoutes = [
  '',
  '/cyber-cafe',
  '/name-date-on-photo',
  '/photo-resizer-20kb',
  '/photo-resizer-30kb',
  '/photo-resizer-50kb',
  '/photo-resizer-100kb',
  '/photo-resizer-150kb',
  '/photo-resizer-200kb',
  '/photo-tools',
  '/signature-tools',
  '/pdf-tools',
  '/form-tools',
  '/image-tools'
];

const urlSet = new Set(coreRoutes.map((r) => `https://${HOST}${r}`));

// 2. Load all 805+ generated tools
try {
  const autoToolsPath = path.join(__dirname, '../lib/autoGeneratedTools.json');
  if (fs.existsSync(autoToolsPath)) {
    const autoTools = JSON.parse(fs.readFileSync(autoToolsPath, 'utf8'));
    autoTools.forEach((tool) => {
      if (tool.slug) {
        const cleanSlug = tool.slug.startsWith('/') ? tool.slug : `/${tool.slug}`;
        urlSet.add(`https://${HOST}${cleanSlug}`);
      }
    });
  }
} catch (err) {
  console.warn('Warning: lib/autoGeneratedTools.json load error:', err.message);
}

// 3. Load exam preset routes
try {
  const examPresetsPath = path.join(__dirname, '../data/exam-presets.json');
  if (fs.existsSync(examPresetsPath)) {
    const examPresets = JSON.parse(fs.readFileSync(examPresetsPath, 'utf8'));
    examPresets.forEach((exam) => {
      if (exam.slug) {
        const cleanSlug = exam.slug.startsWith('/') ? exam.slug : `/exam/${exam.slug}`;
        urlSet.add(`https://${HOST}${cleanSlug}`);
      }
    });
  }
} catch (err) {
  console.warn('Warning: data/exam-presets.json load error:', err.message);
}

const fullUrlList = Array.from(urlSet);

function sendBatch(urls) {
  return new Promise((resolve, reject) => {
    const payload = JSON.stringify({
      host: HOST,
      key: KEY,
      keyLocation: KEY_LOCATION,
      urlList: urls
    });

    const options = {
      hostname: 'api.indexnow.org',
      port: 443,
      path: '/indexnow',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json; charset=utf-8',
        'Content-Length': Buffer.byteLength(payload)
      }
    };

    const req = https.request(options, (res) => {
      let responseBody = '';
      res.on('data', (chunk) => (responseBody += chunk));
      res.on('end', () => {
        if (res.statusCode === 200 || res.statusCode === 202) {
          console.log(`✅ IndexNow Ping Successful! Status: ${res.statusCode} (${urls.length} URLs sent)`);
          resolve(true);
        } else {
          console.log(`⚠️ Status: ${res.statusCode} | Info: ${responseBody || 'Submitted'}`);
          resolve(false);
        }
      });
    });

    req.on('error', (err) => {
      console.error('❌ Ping error:', err.message);
      reject(err);
    });

    req.write(payload);
    req.end();
  });
}

async function submitIndexNow() {
  console.log(`🚀 Formilo SEO Index Engine: Queuing ${fullUrlList.length} unique live URLs...`);
  
  const BATCH_SIZE = 1000;
  for (let i = 0; i < fullUrlList.length; i += BATCH_SIZE) {
    const batch = fullUrlList.slice(i, i + BATCH_SIZE);
    await sendBatch(batch);
  }
  
  console.log('✨ All search engines notified successfully!');
}

submitIndexNow();
